_crash_add:
    pattern:  /crash/add
    defaults: { _controller: JMBTechnologyBrokenOpenAppCoreBundle:IncomingCrashACRA:add }
    methods:  [POST]

_main_dashboard:
    pattern:  /
    defaults: { _controller: JMBTechnologyBrokenOpenAppCoreBundle:DashBoard:index }
    methods:  [GET]

_project_new:
    pattern:  /project/new
    defaults: { _controller: JMBTechnologyBrokenOpenAppCoreBundle:ProjectNew:index }
    methods:  [GET,POST]

_project_index:
    pattern:  /project/{projectId}
    defaults: { _controller: JMBTechnologyBrokenOpenAppCoreBundle:Project:index }
    methods:  [GET]
    requirements:
        projectId: \d+


_project_app_index:
    pattern:  /project/{projectId}/application/{packageName}
    defaults: { _controller: JMBTechnologyBrokenOpenAppCoreBundle:ProjectApplication:index }
    methods:  [GET]
    requirements:
        packageName: "[0-9a-zA-Z\.]+"
        projectId: \d+


_project_issue_index:
    pattern:  /project/{projectId}/issue/{issueId}
    defaults: { _controller: JMBTechnologyBrokenOpenAppCoreBundle:ProjectIssue:index, issueId: a }
    methods:  [GET]
    requirements:
        issueId: "[0-9a-fA-F]{32}"
        projectId: \d+

_project_issue_edittitle:
    pattern:  /project/{projectId}/issue/{issueId}/edittitle
    defaults: { _controller: JMBTechnologyBrokenOpenAppCoreBundle:ProjectIssue:editTitle, issueId: a }
    methods:  [GET,POST]
    requirements:
        issueId: "[0-9a-fA-F]{32}"
        projectId: \d+

_project_crash_index:
    pattern:  /project/{projectId}/crash/{crashId}
    defaults: { _controller: JMBTechnologyBrokenOpenAppCoreBundle:ProjectCrash:index }
    methods:  [GET]
    requirements:
        id: \d+
        projectId: \d+

#_crash_test_data:
#    pattern:  /crash/generate_data
#    defaults: { _controller: JMBTechnologyBrokenOpenAppCoreBundle:Crash:generateTestData }
#    methods:  [GET]

account_register:
    path:     /register
    defaults: { _controller: JMBTechnologyBrokenOpenAppCoreBundle:UserRegister:register }

account_create:
    path:     /register/create
    defaults: { _controller: JMBTechnologyBrokenOpenAppCoreBundle:UserRegister:create }

account_login:
    path:     /login
    defaults: { _controller: JMBTechnologyBrokenOpenAppCoreBundle:UserLogin:login }

account_login_check:
    path:     /login/check
    defaults: { _controller: JMBTechnologyBrokenOpenAppCoreBundle:UserLogin:check }

account_logout:
    path:   /logout

