language: php
php:
  - "5.6"
  - "5.5"
  - "5.4"

services: PostgreSQL


before_script:
  - composer install --dev --no-interaction
  - psql -c 'create database brokenopenapptest;' -U postgres
  - cp .travis.parameters_test.pgsql.yml app/config/parameters_test.yml


script: phpunit  --configuration app/phpunit.xml

