jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        JMBTechnology\BrokenOpenAppCoreBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        our_db_provider:
            entity:
                class: JMBTechnologyBrokenOpenAppCoreBundle:User
                property: email

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH, ROLE_CREATE_PROJECT]

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            pattern:    ^/
            anonymous:    true
            provider: our_db_provider
            form_login:
                login_path: /login
                check_path: /login/check
            logout:
                path: /logout
                target: /login


    access_control:
        - { path: ^/$, roles: ROLE_USER }
        - { path: ^/project, roles: ROLE_USER }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login/check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/crash, roles: IS_AUTHENTICATED_ANONYMOUSLY }
