_crash_add:
    pattern:  /crash/add
    defaults: { _controller: MLabsAcraServerBundle:IncomingCrash:add }
    methods:  [POST]

_main_dashboard:
    pattern:  /dashboard
    defaults: { _controller: MLabsAcraServerBundle:DashBoard:index }
    methods:  [GET]

_project_index:
    pattern:  /project/{projectId}
    defaults: { _controller: MLabsAcraServerBundle:Project:index }
    methods:  [GET]
    requirements:
        projectId: \d+


_project_app_index:
    pattern:  /project/{projectId}/application/{packageName}
    defaults: { _controller: MLabsAcraServerBundle:ProjectApplication:index }
    methods:  [GET]
    requirements:
        packageName: "[0-9a-zA-Z\.]+"
        projectId: \d+


_project_issue_index:
    pattern:  /project/{projectId}/issue/{issueId}
    defaults: { _controller: MLabsAcraServerBundle:ProjectIssue:index, issueId: a }
    methods:  [GET]
    requirements:
        issueId: "[0-9a-fA-F]{32}"
        projectId: \d+

_project_issue_edittitle:
    pattern:  /project/{projectId}/issue/{issueId}/edittitle
    defaults: { _controller: MLabsAcraServerBundle:ProjectIssue:editTitle, issueId: a }
    methods:  [GET,POST]
    requirements:
        issueId: "[0-9a-fA-F]{32}"
        projectId: \d+

_project_crash_index:
    pattern:  /project/{projectId}/crash/details/{crashId}
    defaults: { _controller: MLabsAcraServerBundle:ProjectCrash:index }
    methods:  [GET]
    requirements:
        id: \d+
        projectId: \d+

#_crash_test_data:
#    pattern:  /crash/generate_data
#    defaults: { _controller: MLabsAcraServerBundle:Crash:generateTestData }
#    methods:  [GET]
